analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-XY1V8C4KZE"
    anonymize_ip         : # true, false (default)
